:art: Added fade animation to cards
cesium/cesium.link pull request #42
Opened 2022-03-19 14:08 UTC by RicAlvesO

If applied will add a new animation to selected/hovered cards in the cesium.link website.

2022-04-03 19:47 UTC, nelsonmestevao commented on components/Card/style.module.css
> +  transition: color 0.5s ease, background-color 0.5s ease, border-color 0.5s ease;
These much transition time makes the website feel slow. Could you try a smaller value, please?

2022-04-03 19:49 UTC, nelsonmestevao commented on components/Card/style.module.css
> +  background-color: orange;
I like the upgrade to orange to make it more consist with our branding. However, I dislike the orange fill. Could you try orange as border color?

What about adding some animation effect on mouse hover, live rotating, shaking or something else?

2022-04-03 19:49 UTC, nelsonmestevao requested changes
Thank you for your first contribution :orange_heart: 

Could you check my comments, please? :pray:

2022-04-04 08:20 UTC, RicAlvesO commented
Following the much appreciated feedback the button animation was changed. Transitions are back to .15s and background color is back to white.

As suggested, border and text color are now orange to be more in line with the brand, the new animation makes the orange color slide through the button as the color changes, disappearing right after.

2022-04-05 11:15 UTC, nelsonmestevao approved these changes
:rocket: 

Thanks again for this :pray:

2022-04-05 11:15 UTC, merged